@startwbs
* 自販機シュミレーションを作る
** 外見を作る
*** 自販機を背景にする
*** 商品選択ボタンを貼る
*** 投入金額ラベルを貼る
*** おつり返金ラベルを貼る
*** 商品購入ラベルを貼る
*** 貨幣ボタンを貼る
*** おつり返金ボタンを貼る
*** 商品出力ラベルを貼る
** 関数を作る
*** 商品選択ボタンの処理
*** おつり返金ボタンの処理
*** 貨幣ボタンの処理

@endwbs
